### ISSUE TITLE
thoughts on xdotool?

### ISSUE THREAD

**Issue by sewnie** [alpheratz0/xhsr#1]
xdotool is a simple X tool that can do many many actions, one of them being `xhsr`,
```
~ $ xdotool getactivewindow
8388614
```
it also has many many other actions too!

however, what i really really suggest is to make a very simple alternative (much like xscreenshot and xhsr) - to [slop](https://github.com/naelstrof/slop)

**Comment by alpheratz0** [comment]
Well, xhsr gets the *root window* of the hovered window, while xdotool getactivewindow gets the active window (not the root, not the hovered)

An alternative to slop? mmm, yeah I could try

**Comment by sewnie** [comment]
> xhsr gets the root window of the hovered window

what the fart

**Comment by alpheratz0** [comment]
> what the fart

Whats wrong? It first gets the hovered window (the window on which the mouse is over) and then gets the [root window](https://en.wikipedia.org/wiki/Root_window) of that window
